export interface Transaction {
    id: string;
    timestamp: string;
    sender: string;
    receiver: string;
    type: "FIAT" | "CRYPTO" | "STOCKS" | "SYSTEM";
    subType: string;
    amount: number;
    currency: string;
    feeCollected: number;
    status: "COMPLETED" | "PENDING" | "FAILED" | "CANCELLED" | "FLAGGED";
    riskScore: "LOW" | "MEDIUM" | "HIGH";
    networkIp?: string;
    payloadHash?: string;
}

export const mockAdminStats = {
    globalCounters: {
        total: 14205,
        pending: 12,
        accepted: 13950,
        denied: 243,
    },
    amlCompliance: {
        flaggedCount: "4 Active Alerts",
        flaggedSubtext: "3 New Accounts (High-Risk) | 1 Unusual Volume",
        failureRate: "1.42%",
        failureSubtext: "Stripe: OK | Plaid: High Latency (+12%)",
    },
    systemHealth: {
        omnibusFiat: "€12.45M / €12.43M",
        omnibusSubtext: "Bank: €12.45M | Virtual Client: €12.43M (Matched)",
        cryptoLiquidity: "42.50 BTC / 350.00 BTC",
        cryptoSubtext: "Hot: 42.5 BTC (Ready) | Cold: 350 BTC (Secured)",
    },
    financialPerformance: {
        totalVolume: "€3.84M",
        volumeSubtext: "24h: €1.2M | 7d: €8.4M | 30d: €34.2M",
        feesCollected: "€48,250",
        feesSubtext: "Fiat: €22.1K | Crypto: €18.4K | Stocks: €7.7K",
    },
};

export const mockTransactions: Transaction[] = [
    {
        id: "TXN-908231-X",
        timestamp: "2026-06-24 13:42:11",
        sender: "Alexandru Popescu",
        receiver: "Binance ColdWallet 4",
        type: "CRYPTO",
        subType: "On-chain Withdrawal",
        amount: 0.45,
        currency: "BTC",
        feeCollected: 0.00015,
        status: "FLAGGED",
        riskScore: "HIGH",
        networkIp: "185.212.114.2",
        payloadHash: "0x7a8b9c...eef42",
    },
    {
        id: "TXN-110294-F",
        timestamp: "2026-06-24 13:40:05",
        sender: "Elena Radu",
        receiver: "System Ledger (RON)",
        type: "FIAT",
        subType: "Top-up (Card)",
        amount: 2500.0,
        currency: "RON",
        feeCollected: 25.0,
        status: "COMPLETED",
        riskScore: "LOW",
        networkIp: "82.79.12.194",
        payloadHash: "0xf42d1a...bb109",
    },
    {
        id: "TXN-554219-S",
        timestamp: "2026-06-24 13:35:59",
        sender: "Mihai Toma",
        receiver: "NASDAQ Execution Node",
        type: "STOCKS",
        subType: "Buy Order (AAPL)",
        amount: 1850.5,
        currency: "USD",
        feeCollected: 2.5,
        status: "PENDING",
        riskScore: "MEDIUM",
        networkIp: "193.22.45.12",
        payloadHash: "0x112bcf...aa882",
    },
    {
        id: "TXN-002914-SYS",
        timestamp: "2026-06-24 13:30:00",
        sender: "Automated Fee Engine",
        receiver: "Platform Treasury Vault",
        type: "SYSTEM",
        subType: "Fee Collection",
        amount: 482.1,
        currency: "EUR",
        feeCollected: 0.0,
        status: "COMPLETED",
        riskScore: "LOW",
        networkIp: "127.0.0.1 (Internal)",
        payloadHash: "0x000000...sys88",
    },
    // --- 20 NEW ADDITIONS BELOW ---
    {
        id: "TXN-882194-C",
        timestamp: "2026-06-24 14:12:03",
        sender: "Kraken Outflow Node 2",
        receiver: "Andrei Diaconu",
        type: "CRYPTO",
        subType: "On-chain Deposit",
        amount: 14.25,
        currency: "ETH",
        feeCollected: 0.0042,
        status: "COMPLETED",
        riskScore: "LOW",
        networkIp: "195.43.22.81",
        payloadHash: "0x8c3b1a...fe001",
    },
    {
        id: "TXN-304912-F",
        timestamp: "2026-06-24 14:05:44",
        sender: "George Marinescu",
        receiver: "Revolut Gateway Euro",
        type: "FIAT",
        subType: "SEPA Instant Outbound",
        amount: 4350.0,
        currency: "EUR",
        feeCollected: 4.5,
        status: "PENDING",
        riskScore: "LOW",
        networkIp: "86.120.44.112",
        payloadHash: "0xa12b88...cc401",
    },
    {
        id: "TXN-773210-S",
        timestamp: "2026-06-24 13:58:19",
        sender: "Anca Ionescu",
        receiver: "NYSE Execution Clearing",
        type: "STOCKS",
        subType: "Sell Order (NVDA)",
        amount: 12450.0,
        currency: "USD",
        feeCollected: 18.2,
        status: "COMPLETED",
        riskScore: "LOW",
        networkIp: "5.12.99.234",
        payloadHash: "0x992bcf...dd112",
    },
    {
        id: "TXN-449102-SYS",
        timestamp: "2026-06-24 13:55:00",
        sender: "Yield Rebalancing Oracle",
        receiver: "Staking Pool Alpha",
        type: "SYSTEM",
        subType: "Liquidity Reallocation",
        amount: 75000.0,
        currency: "USDC",
        feeCollected: 0.0,
        status: "COMPLETED",
        riskScore: "LOW",
        networkIp: "127.0.0.1 (Internal)",
        payloadHash: "0x000aa1...sys99",
    },
    {
        id: "TXN-661029-C",
        timestamp: "2026-06-24 13:48:32",
        sender: "Unknown External Wallet",
        receiver: "Premium Client Holding Vault",
        type: "CRYPTO",
        subType: "Whale Inbound Transfer",
        amount: 450.0,
        currency: "SOL",
        feeCollected: 0.012,
        status: "FLAGGED",
        riskScore: "HIGH",
        networkIp: "45.132.22.19",
        payloadHash: "0x44fa2b...ee918",
    },
    {
        id: "TXN-129481-F",
        timestamp: "2026-06-24 13:22:10",
        sender: "Ionut Vasile",
        receiver: "Merchant Processing Node",
        type: "FIAT",
        subType: "E-Commerce Payment",
        amount: 890.0,
        currency: "RON",
        feeCollected: 1.2,
        status: "FAILED",
        riskScore: "LOW",
        networkIp: "109.166.43.12",
        payloadHash: "0xcc219a...bb994",
    },
    {
        id: "TXN-902184-S",
        timestamp: "2026-06-24 13:15:02",
        sender: "Laura Dumitru",
        receiver: "NASDAQ Execution Node",
        type: "STOCKS",
        subType: "Buy Order (TSLA)",
        amount: 3200.0,
        currency: "USD",
        feeCollected: 4.1,
        status: "CANCELLED",
        riskScore: "LOW",
        networkIp: "82.76.221.15",
        payloadHash: "0x8831ef...aa291",
    },
    {
        id: "TXN-551029-C",
        timestamp: "2026-06-24 12:55:41",
        sender: "Marius Nistor",
        receiver: "KuCoin Deposit Address",
        type: "CRYPTO",
        subType: "Cross-chain Bridge Send",
        amount: 15400.0,
        currency: "USDT",
        feeCollected: 15.0,
        status: "COMPLETED",
        riskScore: "MEDIUM",
        networkIp: "185.190.140.4",
        payloadHash: "0x33bda1...ff512",
    },
    {
        id: "TXN-334910-F",
        timestamp: "2026-06-24 12:41:19",
        sender: "UK Corporate Settlement Ltd",
        receiver: "Omnibus GBP Pool",
        type: "FIAT",
        subType: "CHAPS High-Value Inbound",
        amount: 85000.0,
        currency: "GBP",
        feeCollected: 45.0,
        status: "COMPLETED",
        riskScore: "MEDIUM",
        networkIp: "194.22.118.9",
        payloadHash: "0xdd381f...ee204",
    },
    {
        id: "TXN-002915-SYS",
        timestamp: "2026-06-24 12:30:00",
        sender: "Sovereign AML Risk Engine",
        receiver: "Quarantine Registry Node",
        type: "SYSTEM",
        subType: "Automated Fraud Lock",
        amount: 0.0,
        currency: "SYS",
        feeCollected: 0.0,
        status: "COMPLETED",
        riskScore: "LOW",
        networkIp: "127.0.0.1 (Internal)",
        payloadHash: "0x000000...aml01",
    },
    {
        id: "TXN-881942-S",
        timestamp: "2026-06-24 11:50:22",
        sender: "NYSE Execution Clearing",
        receiver: "Cristina Matei",
        type: "STOCKS",
        subType: "Dividend Distribution (MSFT)",
        amount: 142.8,
        currency: "USD",
        feeCollected: 0.0,
        status: "COMPLETED",
        riskScore: "LOW",
        networkIp: "213.233.91.45",
        payloadHash: "0x114aba...ff991",
    },
    {
        id: "TXN-710294-C",
        timestamp: "2026-06-24 11:24:15",
        sender: "Stefan Stoica",
        receiver: "TornadoCash Intercept Mirror",
        type: "CRYPTO",
        subType: "Privacy Mixer Interaction",
        amount: 1.85,
        currency: "ETH",
        feeCollected: 0.015,
        status: "FLAGGED",
        riskScore: "HIGH",
        networkIp: "93.115.22.4",
        payloadHash: "0xdeadbe...ef026",
    },
    {
        id: "TXN-224910-F",
        timestamp: "2026-06-24 10:55:01",
        sender: "Raluca Albu",
        receiver: "System Ledger (EUR)",
        type: "FIAT",
        subType: "SWIFT International Wire",
        amount: 11000.0,
        currency: "EUR",
        feeCollected: 20.0,
        status: "PENDING",
        riskScore: "MEDIUM",
        networkIp: "86.122.90.13",
        payloadHash: "0xbb7712...cc884",
    },
    {
        id: "TXN-663810-S",
        timestamp: "2026-06-24 10:14:55",
        sender: "Bogdan Stancu",
        receiver: "CBOE Options Pipeline",
        type: "STOCKS",
        subType: "Options Contract Buy (AMZN)",
        amount: 4500.0,
        currency: "USD",
        feeCollected: 12.5,
        status: "COMPLETED",
        riskScore: "MEDIUM",
        networkIp: "5.2.140.88",
        payloadHash: "0x772bba...dd910",
    },
    {
        id: "TXN-002916-SYS",
        timestamp: "2026-06-24 10:00:00",
        sender: "Platform Treasury Vault",
        receiver: "Hot Wallet Liquidity Pool",
        type: "SYSTEM",
        subType: "Gas Rebalancing Sweep",
        amount: 5.0,
        currency: "ETH",
        feeCollected: 0.0,
        status: "COMPLETED",
        riskScore: "LOW",
        networkIp: "127.0.0.1 (Internal)",
        payloadHash: "0x000000...eth55",
    },
    {
        id: "TXN-104921-F",
        timestamp: "2026-06-24 09:41:12",
        sender: "Vlad Teodorescu",
        receiver: "ATM Cashout Center (Bucuresti)",
        type: "FIAT",
        subType: "Voucher Redeem Withdrawal",
        amount: 4000.0,
        currency: "RON",
        feeCollected: 40.0,
        status: "COMPLETED",
        riskScore: "LOW",
        networkIp: "82.79.40.215",
        payloadHash: "0xff2211...ab009",
    },
    {
        id: "TXN-550192-C",
        timestamp: "2026-06-24 09:12:05",
        sender: "Coinbase Prime Custody",
        receiver: "Platform Arbitrage Liquidity",
        type: "CRYPTO",
        subType: "Internal Institutional Mint",
        amount: 2.15,
        currency: "BTC",
        feeCollected: 0.0,
        status: "COMPLETED",
        riskScore: "LOW",
        networkIp: "64.233.16.4",
        payloadHash: "0x8a9b1c...ff324",
    },
    {
        id: "TXN-391024-S",
        timestamp: "2026-06-24 08:59:44",
        sender: "NYSE Execution Clearing",
        receiver: "Diana Rus",
        type: "STOCKS",
        subType: "Fractional Share Sell (META)",
        amount: 420.5,
        currency: "USD",
        feeCollected: 0.85,
        status: "COMPLETED",
        riskScore: "LOW",
        networkIp: "109.100.12.33",
        payloadHash: "0xcc4412...ee881",
    },
    {
        id: "TXN-884910-F",
        timestamp: "2026-06-24 08:31:10",
        sender: "Unknown Proxy Cardholder",
        receiver: "System Ledger (USD)",
        type: "FIAT",
        subType: "Stripe Gateway Top-up",
        amount: 5000.0,
        currency: "USD",
        feeCollected: 150.0,
        status: "FAILED",
        riskScore: "HIGH",
        networkIp: "103.241.12.91",
        payloadHash: "0xfa1122...cc901",
    },
    {
        id: "TXN-002917-SYS",
        timestamp: "2026-06-24 08:00:00",
        sender: "Automated Yield Engine",
        receiver: "All Active Crypto Stakers",
        type: "SYSTEM",
        subType: "Staking Reward Distribution",
        amount: 1450.25,
        currency: "USDC",
        feeCollected: 0.0,
        status: "COMPLETED",
        riskScore: "LOW",
        networkIp: "127.0.0.1 (Internal)",
        payloadHash: "0x000000...dist8",
    },
];
